import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wallaclone</title>
        <meta name="description" content="Generated by the nameless team" />
       
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to WALLACLONE
        </h1>

        <p className={styles.description}>
          Una aplicación creada por:{' '}
          <code className={styles.code}>nameless-team.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/AdrianValenzuela" className={styles.card}>
            <h2>Adrián Valenzuela Guasp &rarr;</h2>
            <p>Backend y agile master. El mejor project manager</p>
          </a>

          <a href="https://github.com/lmhmDev" className={styles.card}>
            <h2>Lorenzo Hermoso Moreno &rarr;</h2>
            <p>Frontend master and extremely reactive</p>
          </a>

          <a
            href="https://github.com/orgs/ProyectoFinal-Wallaclone/people/NandoLT"
            className={styles.card}
          >
            <h2>Fernando Lopez Trejo &rarr;</h2>
            <p>Backend Master and token fanatics</p>
          </a>

          <a
            href="https://github.com/orgs/ProyectoFinal-Wallaclone/people/jaimeperezortega"
            className={styles.card}
          >
            <h2>Jaime Pérez Ortega &rarr;</h2>
            <p>
              Master og nothing and fake afro hair in his github profile
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
      
          Powered by{' '}
          <span className={styles.logo}>
           THE NAMELESS TEAM
          </span>
        
      </footer>
    </div>
  )
}
