import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import {authLogin, authLogout} from '../store/actions'


export default function Home() {
  return (

   

        <div className={styles.container}>
              <Head>
                <title>Wallaclone</title>
                <meta name="description" content="Generated by the nameless team" />
              
              </Head>

              <main className={styles.main}>
                <h1 className={styles.title}>
                  Welcome to <span className="team-title"> WALLACLONE </span> 
                </h1>

                <div className={styles.grid}>
                
                  <div className={styles.card} >
                  <h3> <Link className={styles.card} href='/login'> Login Page &rarr; </Link> </h3>
                  </div>

                  <div className={styles.card} >
                  <h3> <Link className={styles.card} href='/register'> Register Page &rarr; </Link> </h3>
                  </div>

                  <div className={styles.card} >
                  <h3> <Link className={styles.card} href='/adverts'> Adverts Page &rarr; </Link> </h3>
                  </div>

               
                </div>
              </main>

              <style jsx>{`
                    
                    h3{
                        color:#09f;
                    }
                    .team-title{
                      color:#09f;
                    }

                    `}</style>

              <footer className={styles.footer}>
              
                  Powered by{' '}
                  <span className={styles.logo}>
                  THE NAMELESS TEAM
                  </span>
                
              </footer>
            </div>

    
   
  )
}
