
export const AUTH_REGISTER = 'AUTH_REGISTER';

export const AUTH_LOGIN = 'AUTH_LOGIN';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE  = 'AUTH_LOGIN_FAILURE';


export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_REQUEST = ' AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_RESET_STATE = 'AUTH_RESET_STATE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADVERTS_GET = 'ADVERTS_GET';

