
export const AUTH_REGISTER = 'AUTH_REGISTER';

export const AUTH_LOGIN = 'AUTH_LOGIN';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';


export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_REQUEST = ' AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_RESET_STATE = 'AUTH_RESET_STATE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_ADVERTS_SUCCESS = 'GET_ADVERTS_SUCCESS';
export const GET_ADVERTS_REQUEST = 'GET_ADVERTS_REQUEST';
export const GET_ADVERTS_FAILURE = 'GET_ADVERTS_FAILURE';

export const ADVERT_CREATION_REQUEST = 'ADVERT_CREATION_REQUEST';
export const ADVERT_CREATION_SUCCESS = 'ADVERT_CREATION-SUCCESS';
export const ADVERT_CREATION_FAILURE = 'ADVERT_CREATION_FAILURE';

export const ADVERT_GET_FAVORITES_REQUEST = 'ADVERT_GET_FAVORITES_REQUEST';
export const ADVERT_GET_FAVORITES_SUCCESS = 'ADVERT_GET_FAVORITES_SUCCESS';
export const ADVERT_GET_FAVORITES_FAILURE = 'ADVERT_GET_FAVORITES_FAILURE';

export const ADVERT_ADD_FAVORITE_REQUEST = 'ADVERT_ADD_FAVORITE_REQUEST';
export const ADVERT_ADD_FAVORITE_SUCCESS = 'ADVERT_ADD_FAVORITE_SUCCESS';
export const ADVERT_ADD_FAVORITE_FAILURE = 'ADVERT_ADD_FAVORITE_FAILURE';

export const ADVERT_DELETE_FAVORITE_REQUEST = 'ADVERT_DELETE_FAVORITE_REQUEST';
export const ADVERT_DELETE_FAVORITE_SUCCESS = 'ADVERT_DELETE_FAVORITE_SUCCESS';
export const ADVERT_DELETE_FAVORITE_FAILURE = 'ADVERT_DELETE_FAVORITE_FAILURE';

export const ADVERT_UPDATE_REQUEST = ' ADVERT_UPDATE_REQUEST';
export const ADVERT_UPDATE_SUCCESS = ' ADVERT_UPDATE_SUCCESS';
export const ADVERT_UPDATE_FAILURE = ' ADVERT_UPDATE_FAILURE';

export const AUTH_RECOVER_PASSWORD_REQUEST = ' AUTH_RECOVER_PASSWORD_REQUEST';
export const AUTH_RECOVER_PASSWORD_SUCCESS = ' AUTH_RECOVER_PASSWORD_SUCCESS';
export const AUTH_RECOVER_PASSWORD_FAILURE = ' AUTH_RECOVER_PASSWORD_FAILURE';

export const AUTH_RESET_PASSWORD_REQUEST = ' AUTH_RESET_PASSWORD_REQUEST';
export const AUTH_RESET_PASSWORD_SUCCESS = ' AUTH_RESET_PASSWORD_SUCCESS';
export const AUTH_RESET_PASSWORD_FAILURE = 'AUTH_RESET_PASSWORD_FAILURE';

export const CONFIRM_PASSWORD_FAILURE = 'CONFIRM_PASSWORD_FAILURE';

export const FETCH_MY_ADVERTS_REQUEST = "FETCH_MY_ADVERTS_REQUEST ";
export const FETCH_MY_ADVERTS_SUCCESS = "FETCH_MY_ADVERTS_SUCCESS ";
export const FETCH_MY_ADVERTS_FAILURE = "FETCH_MY_ADVERTS_FAILURE ";

export const GET_MY_PROFILE_DETAILS_REQUEST = "GET_MY_PROFILE_DETAILS_REQUEST";
export const GET_MY_PROFILE_DETAILS_SUCCESS = "GET_MY_PROFILE_DETAILS_SUCCESS";
export const GET_MY_PROFILE_DETAILS_FAILURE = "GET_MY_PROFILE_DETAILS_FAILURE";

export const GET_MY_FAVORITE_ADVERTS_REQUEST = "GET_MY_FAVORITE_ADVERTS_REQUEST";
export const GET_MY_FAVORITE_ADVERTS_SUCCESS = "GET_MY_FAVORITE_ADVERTS_SUCCESS";
export const GET_MY_FAVORITE_ADVERTS_FAILURE = "GET_MY_FAVORITE_ADVERTS_FAILURE";

export const GET_MY_CONVERSATIONS_REQUEST = "GET_MY_CONVERSATIONS_REQUEST";
export const GET_MY_CONVERSATIONS_SUCCESS = "GET_MY_CONVERSATIONS_SUCCESS";
export const GET_MY_CONVERSATIONS_FAILURE = "GET_MY_CONVERSATIONS_RFAILURE";

export const GET_CONVERSATION_REQUEST = "GET_CONVERSATION_REQUEST";
export const GET_CONVERSATION_SUCCESS = "GET_CONVERSATION_SUCCESS";
export const GET_CONVERSATION_FAILURE = "GET_CONVERSATION_RFAILURE";

export const CREATE_CONVERSATION_REQUEST = "CREATE_CONVERSATION_REQUEST";
export const CREATE_CONVERSATION_SUCCESS = "CREATE_CONVERSATION_SUCCESS";
export const CREATE_CONVERSATION_FAILURE = "CREATE_CONVERSATION_RFAILURE";

export const ADD_MESSAGE_REQUEST = "ADD_MESSAGE_REQUEST";
export const ADD_MESSAGE_SUCCESS = "ADD_MESSAGE_SUCCESS";
export const ADD_MESSAGE_FAILURE = "ADD_MESSAGE_RFAILURE";